- name: install package
  yum:
    state: latest  
    name: httpd

- name: start httpd daemon
  service:
    state: started
    name: httpd
    enabled: true

- name: Deploy Website
  copy:
    src: ./Playbook\Roles/web-server/files/index.html
    dest: /var/www/html/index.html